apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: final-project-lab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/EduardUsatchev/Final-Project-Lab-E2E.git"
    targetRevision: HEAD
    path: solutions/level1
  destination:
    server: "https://kubernetes.default.svc"
    namespace: devops-lab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
