groups:
- name: sample-app-alerts
  rules:
  - alert: AlwaysFiringTestAlert
    expr: vector(1) > 0
    for: 0s
    labels:
      severity: critical
    annotations:
      summary: "Always firing test alert"
      description: "This alert is automatically triggered for testing purposes."
