global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/rules/prometheus-rules.yml

scrape_configs:
  - job_name: "kubernetes-pods"
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: sample-app
        action: keep
