apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sample-app.name" . }}
    app.kubernetes.io/managed-by: {{ include "sample-app.managedBy" . }}
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 5000
  selector:
    app: {{ include "sample-app.name" . }}
