apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard
data:
  sample-dashboard.json: |
    {
      "annotations": {
        "list": []
      },
      "editable": true,
      "gnetId": null,
      "graphTooltip": 0,
      "id": null,
      "links": [],
      "panels": [
        {
          "datasource": null,
          "fieldConfig": {
            "defaults": {},
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 0
          },
          "id": 2,
          "options": {
            "content": "Welcome to the Sample Grafana Dashboard",
            "mode": "html"
          },
          "targets": [],
          "title": "Welcome Panel",
          "type": "text"
        }
      ],
      "refresh": "5s",
      "schemaVersion": 30,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "Sample Dashboard",
      "uid": "sample-dashboard",
      "version": 1
    }
